name: SD Build v2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DGGML_OPENMP=OFF

      - name: Build
        run: cmake --build build --config Release -j2

      - name: List build output
        run: find build/bin -type f

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: sd-binaries
          path: |
            build/bin/sd-cli
            build/bin/sd-server
